config/routes.rb
Rails.application.routes.draw do
  get 'categoria/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get "user", to: "users#index" 
  get "funcionario", to: "funcionarios#index" 
  get "produto", to: "produtos#show"
  get "categoria/:categoria", to: "categoria#show"
  get "vendas", to: "vendas#new"
  post "vendas", to: "vendas#create"
  get "perfil", to: "perfil#new"
  post "perfil", to: "perfil#create"
  get "cobrancas", to: "cobranca#index" 
  patch "cobranca/:id", to: "cobranca#update" 

  devise_for :funcionarios, 
              controllers: {
                registrations: 'funcionario/registrations',
                sessions: 'funcionario/sessions'
              }
  devise_for :users, 
              controllers: {
                registrations: 'user/registrations'
              }
end

app/views/shared/funcionarios_menu/botoes/_area_funcionario.erb
<% if (request.path.eql?("/admin")) %>
<%= link_to("Area do Funcionario", "/admin", :class=>"bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium",  :'aria-current' =>"page")%>
<% else %>
<%= link_to("Area do Funcionario", "/admin", :class=>"text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium")%>
<% end %>

app/views/shared/funcionarios_menu/botoes/_cobrancas.erb
<% if (request.path.eql?(cobrancas_path)) %>
<%= link_to("Cobrancas", cobrancas_path, :class=>"bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium",  :'aria-current' =>"page")%>
<% else %>
<%= link_to("Cobrancas", cobrancas_path, :class=>"text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium")%>
<% end %>

app/views/shared/funcionarios_menu/botoes/_inicio.erb
<% if (request.path.eql?(root_path)) %>
  <%= link_to("Inicio", root_path, :class=>"bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium",  :'aria-current' =>"page")%>
<% else %>
  <%= link_to("Inicio", root_path, :class=>"text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium")%>
<% end %>