config/routes.rb
Rails.application.routes.draw do
  get 'categoria/show'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'home#index'
  get "user", to: "users#index" 
  get "funcionario", to: "funcionarios#index" 
  get "produto", to: "produtos#show"
  get "categoria/:categoria", to: "categoria#show"
  get "vendas", to: "vendas#new"
  post "vendas", to: "vendas#create"
  get "perfil", to: "perfil#new"
  post "perfil", to: "perfil#create"
  get "cobrancas", to: "cobranca#index" 
  patch "cobranca/:id", to: "cobranca#update" 

  devise_for :funcionarios, 
              controllers: {
                registrations: 'funcionario/registrations',
                sessions: 'funcionario/sessions'
              }
  devise_for :users, 
              controllers: {
                registrations: 'user/registrations'
              }
end

app/views/shared/funcionarios_menu/_menu.erb
<div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
  <button type="button" class="bg-gray-800 p-1 rounded-full text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white">
    <span class="sr-only">View notifications</span>
    <!-- Heroicon name: outline/bell -->
    <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9" />
    </svg>
  </button>

  <!-- Profile dropdown -->
  <div class="ml-3 relative">
    <div>
      <button type="button" class="bg-gray-800 flex text-sm rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" onclick="hide_show(menu_user);">
        <span class="sr-only">Open user menu</span>
        <% if current_funcionario.perfil.avatar.attached? %>
        <div class="image overflow-hidden">
          <%= image_tag(current_funcionario.avatar, :class=>"h-12 w-12 rounded-full")%>
        </div>
        <% else %>
            <%= image_tag("funcionario_ava.png", :class=>"h-12 w-12 rounded-full")%>
        <% end %>
      </button>
    </div>

    <!--
      Dropdown menu, show/hide based on menu state.

      Entering: "transition ease-out duration-100"
        From: "transform opacity-0 scale-95"
        To: "transform opacity-100 scale-100"
      Leaving: "transition ease-in duration-75"
        From: "transform opacity-100 scale-100"
        To: "transform opacity-0 scale-95"
    -->
    <div class="hidden z-10 origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" id="menu_user" aria-labelledby="user-menu-button" tabindex="-1">
      <!-- Active: "bg-gray-100", Not Active: "" -->
      <%= link_to("Perfil", funcionario_path, :class=>"block px-4 py-2 text-sm text-gray-700") %>
      <%= link_to("Atualizar Dados", edit_funcionario_registration_path(id: current_funcionario.id), :class=>"block px-4 py-2 text-sm text-gray-700") %>
      <%= button_to("Sair", destroy_funcionario_session_path, method: :delete, :class=>"block px-4 py-2 text-sm text-gray-700")%>
    </div>
  </div>
</div>

app/views/shared/funcionarios_menu/_navbar.html.erb
<!-- This example requires Tailwind CSS v2.0+ -->
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex items-center justify-between h-16">
      <!-- menu mobi -->

      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">

        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu"  id='navbar-burger' onclick="hide_navbar();">
          <!--
            Icon when menu is closed.

            Heroicon name: outline/menu

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!--
            Icon when menu is open.

            Heroicon name: outline/x

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <!-- menu desk -->

      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex-shrink-0 flex items-center">
          <%= link_to(image_tag("logo_white.png", :class=> "block lg:hidden h-8 w-auto"), root_path)%>
          <%= link_to(image_tag("logo_white.png", :class=> "hidden lg:block h-8 w-auto"), root_path)%>
        </div>
        <div class="hidden sm:block sm:ml-6">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <%= render "shared/funcionarios_menu/botoes/inicio" %>
            <%= render "shared/funcionarios_menu/botoes/area_funcionario" %>
            <% if Funcionario.cargos[current_funcionario.cargo] == Funcionario.cargos[:Administrador] || Funcionario.cargos[current_funcionario.cargo] == Funcionario.cargos[:"Agente de Cobranca"] || Funcionario.cargos[current_funcionario.cargo] == Funcionario.cargos[:"Super-Administrador"] %>
              <%= render "shared/funcionarios_menu/botoes/cobrancas" %>
            <% end %>
          </div>
        </div>
      </div>

      <!-- usuario -->

        <div class="buttons" id='signs'>
          <%= render 'shared/funcionarios_menu/menu' %>
        </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-4 space-y-1 hidden" id="nav-links">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <%= render "shared/funcionarios_menu/botoes_mobile/inicio" %>
      <%= render "shared/funcionarios_menu/botoes_mobile/area_funcionario" %>
      <% if Funcionario.cargos[current_funcionario.cargo] == Funcionario.cargos[:Administrador] || Funcionario.cargos[current_funcionario.cargo] == Funcionario.cargos[:"Agente de Cobranca"] || Funcionario.cargos[current_funcionario.cargo] == Funcionario.cargos[:"Super-Administrador"] %>
        <%= render "shared/funcionarios_menu/botoes_mobile/cobrancas" %>
      <% end %>
    </div>
  </div>
</nav>